# Generated by Django 5.2.4 on 2025-08-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0003_remove_additionalvariable_save_result_solutionview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolutionView',
            new_name='Solution',
        ),
    ]
