# Generated by Django 5.2.4 on 2025-11-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0004_rename_solutionview_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='uniquwe_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
