# Generated by Django 5.2.4 on 2025-11-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0005_variable_uniquwe_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='uniquwe_group',
            new_name='unique_group',
        ),
    ]
