# Generated by Django 5.2.4 on 2025-11-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0006_rename_uniquwe_group_variable_unique_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='display_format',
            field=models.CharField(choices=[('symbolic', 'Symboliczna'), ('numeric', 'Liczbowa'), ('text', 'Tekstowa')], default='numeric', max_length=20),
        ),
    ]
