# Generated by Django 5.2.4 on 2025-12-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0007_alter_answeroption_display_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='split_sign',
            field=models.BooleanField(default=False),
        ),
    ]
