# Generated by Django 5.2.4 on 2025-12-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0008_variable_split_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalvariable',
            name='split_sign',
            field=models.BooleanField(default=False),
        ),
    ]
