# Generated by Django 5.2.4 on 2025-12-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0009_additionalvariable_split_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='without_value',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
