# Generated by Django 5.2.4 on 2026-01-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0010_variable_without_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
