# Generated by Django 5.2.4 on 2026-01-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0011_assignedtask_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedvariable',
            name='split_sign',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
