# Generated by Django 5.2.4 on 2026-01-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0012_usedvariable_split_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedvariable',
            old_name='split_sign',
            new_name='split_values',
        ),
    ]
