# Generated by Django 5.2.4 on 2026-01-20 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0013_rename_split_sign_usedvariable_split_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedvariable',
            name='additional_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_variables', to='matematyka.additionalvariable'),
        ),
    ]
