# Generated by Django 5.2.4 on 2026-01-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0014_usedvariable_additional_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedvariable',
            name='split_values',
            field=models.JSONField(blank=True, default=False),
        ),
    ]
