# Generated by Django 5.2.4 on 2026-01-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0015_alter_usedvariable_split_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedvariable',
            name='split_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
