# Generated by Django 5.2.4 on 2026-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0016_alter_usedvariable_split_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pieces',
            field=models.JSONField(blank=True, help_text='Lista kawałków funkcji do wykresu', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='x_max',
            field=models.FloatField(blank=True, help_text='Prawy zakres osi X', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='x_min',
            field=models.FloatField(blank=True, help_text='Lewy zakres osi X', null=True),
        ),
    ]
