# Generated by Django 5.2.4 on 2026-06-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0018_expectedanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Kolejność luki w zadaniu')),
                ('content', models.TextField(help_text="Tekst luki widoczny dla ucznia (np. 'Rozwiązaniem równania f(x)=3 jest liczba ......')")),
                ('instruction', models.TextField(blank=True, help_text='Dodatkowa instrukcja dla tej konkretnej luki (opcjonalnie)', null=True)),
                ('answer_type', models.CharField(choices=[('numeric', 'Liczba'), ('expression', 'Wyrażenie matematyczne'), ('set', 'Zbiór / Dziedzina / Przedział'), ('text', 'Tekst')], default='numeric', help_text='Typ oczekiwanej odpowiedzi', max_length=30)),
                ('correct_value', models.CharField(help_text="Poprawna odpowiedź (np. '5', 'R \\ {0}', '[0; +∞)', 'x**2 + 1')", max_length=400)),
                ('validation_rules', models.JSONField(blank=True, help_text='Dodatkowe reguły walidacji specyficzne dla tego zadania', null=True)),
                ('points', models.FloatField(default=1.0, help_text='Ile punktów za poprawną odpowiedź na tę lukę')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_blanks', to='matematyka.task')),
            ],
            options={
                'verbose_name': 'Task Blank',
                'verbose_name_plural': 'Task Blanks',
                'ordering': ['order'],
                'unique_together': {('task', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='ExpectedAnswer',
        ),
    ]
