# Generated by Django 5.2.4 on 2026-07-02 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0019_taskblank_delete_expectedanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.FloatField(default=0)),
                ('answer_date', models.DateTimeField(auto_now_add=True)),
                ('expected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matematyka.taskblank')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_answers', to='matematyka.useranswer')),
            ],
            options={
                'ordering': ['expected_answer'],
                'unique_together': {('user_answer', 'expected_answer')},
            },
        ),
    ]
