# Generated by Django 5.2.4 on 2026-07-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0020_userblankanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblankanswer',
            name='answer_date',
        ),
    ]
