# Generated by Django 5.2.4 on 2026-07-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0021_remove_userblankanswer_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='pieces',
            field=models.JSONField(blank=True, help_text='Wspólny wykres dla grupy zadań', null=True),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='x_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='x_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
