# Generated by Django 5.2.4 on 2026-07-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0022_taskgroup_pieces_taskgroup_x_max_taskgroup_x_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='shared_content',
            field=models.TextField(),
        ),
    ]
