# Generated by Django 5.2.4 on 2026-07-23 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0023_alter_taskgroup_shared_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='variable',
            name='task_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='matematyka.taskgroup'),
        ),
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task__isnull', False), ('task_group__isnull', True)), models.Q(('task__isnull', True), ('task_group__isnull', False)), _connector='OR'), name='variable_exclusive_assignment'),
        ),
    ]
