# Generated by Django 5.2.4 on 2026-07-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0024_alter_variable_unique_together_variable_task_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalvariable',
            name='task_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_variables', to='matematyka.taskgroup'),
        ),
        migrations.AlterField(
            model_name='additionalvariable',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_variables', to='matematyka.task'),
        ),
    ]
