# Generated by Django 5.2.4 on 2026-07-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0025_additionalvariable_task_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalseStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Treść zdania')),
                ('is_true', models.BooleanField(help_text='Czy zdanie jest prawdziwe?')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_statements', to='matematyka.task')),
            ],
        ),
    ]
