# Generated by Django 5.2.4 on 2026-07-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0026_truefalsestatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='truefalsestatement',
            name='sub_number',
            field=models.IntegerField(blank=True, help_text='Numer podzadania w zadaniu typu Prawda/Fałsz', null=True),
        ),
    ]
