# Generated by Django 5.2.4 on 2026-07-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0027_truefalsestatement_sub_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truefalsestatement',
            old_name='is_true',
            new_name='is_correct',
        ),
    ]
