# Generated by Django 5.2.4 on 2026-08-13 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0028_rename_is_true_truefalsestatement_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(help_text='Początek przedziału', max_length=100)),
                ('end', models.CharField(help_text='Koniec przedziału', max_length=100)),
                ('is_closed_start', models.BooleanField(default=True, help_text='Czy przedział jest domknięty z lewej strony?')),
                ('is_closed_end', models.BooleanField(default=True, help_text='Czy przedział jest domknięty z prawej strony?')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='matematyka.task')),
                ('task_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='matematyka.taskgroup')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOptionInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_option_intervals', to='matematyka.answeroption')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_option_intervals', to='matematyka.interval')),
            ],
        ),
    ]
