# Generated by Django 5.2.4 on 2026-08-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0029_interval_answeroptioninterval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='x_max',
            field=models.CharField(blank=True, help_text='Prawy zakres osi X', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='x_min',
            field=models.CharField(blank=True, help_text='Lewy zakres osi X', null=True),
        ),
    ]
