# Generated by Django 5.2.4 on 2026-08-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0030_alter_task_x_max_alter_task_x_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='x_max',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='x_min',
            field=models.CharField(blank=True, null=True),
        ),
    ]
