# Generated by Django 5.2.4 on 2026-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematyka', '0031_alter_taskgroup_x_max_alter_taskgroup_x_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
